### PR TITLE
QueryQueueTimeInMillis

### PR DESCRIPTION
**Pull request by navi86**
Add property QueryQueueTimeInMillis for analysing what is cause of too long execution request

### CODE REVIEW

**Comment by navi86** [comment]
@laughingman7743 I don't understand how tests should pass if env "AWS_ATHENA_S3_STAGING_DIR" is not configured during execution Travis CI.
Could you help me to fix tests ?

**Comment by laughingman7743** [comment]
Secret environment variables cannot be used in PR from a fork. 😩 
https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables

You will need to configure TravisCI in your own forked repository to run the tests.

**Comment by navi86** [comment]
I have run test locally and almost all passed except three which were finished with error:
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: WorkGroup test-pyathena is not found.
I don't think that my changes cause that issue.
is it ok @laughingman7743 ?

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena#testing
> And you need to create a workgroup named test-pyathena with the Query result location configuration.

Your changes are related to the testing around here.
https://github.com/laughingman7743/PyAthena/blob/master/tests/test_model.py#L9-L53
Write a test to make sure the change is okay.

**Comment by navi86** [comment]
@laughingman7743 I've  added tests and they all passed:
`
pipenv run pytest                     
====================================================================================== test session starts =======================================================================================
platform darwin -- Python 3.8.1, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /Users/ivan/PyAthena, inifile: setup.cfg
plugins: isort-1.0.0, black-0.3.8, flake8-1.0.5, xdist-1.31.0, forked-1.1.3, cov-2.8.1
collected 148 items                                                                                                                                                                              

tests/test_async_cursor.py ..............                                                                                                                                                  [  9%]
tests/test_async_pandas_cursor.py .................                                                                                                                                        [ 20%]
tests/test_cursor.py ......................................                                                                                                                                [ 46%]
tests/test_formatter.py .....................                                                                                                                                              [ 60%]
tests/test_model.py ...                                                                                                                                                                    [ 62%]
tests/test_pandas_cursor.py .......................                                                                                                                                        [ 78%]
tests/test_sqlalchemy_athena.py ....................                                                                                                                                       [ 91%]
tests/test_util.py ............                                                                                                                                                            [100%]

======================================================================================== warnings summary ========================================================================================
venv/lib/python3.8/site-packages/boto3/resources/params.py:22
  /Users/ivan/PyAthena/venv/lib/python3.8/site-packages/boto3/resources/params.py:22: DeprecationWarning: invalid escape sequence \[
    INDEX_RE = re.compile("\[(.*)\]$")

tests/test_sqlalchemy_athena.py::TestSQLAlchemyAthena::test_reflect_select
  /Users/ivan/PyAthena/venv/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py:659: SAWarning: Dialect awsathena+rest does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
    util.warn(

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================================== 148 passed, 2 warnings in 493.37s (0:08:13) ===========================================================================
`

**Pull request merged**
