### PR TITLE
adding back dbapi module for backward compatibility with sqlalchemy 1.4.x

### PR DESCRIPTION
**Pull request by mdeshmu**
Fixes https://github.com/laughingman7743/PyAthena/issues/447

### CODE REVIEW

**Review by laughingman7743 — APPROVED** [review]
LGTM

**Comment by seanlane** [comment]
@laughingman7743 it looks like this was reverted, is there a plan to add it back?

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/issues/447#issuecomment-1568735014

**Comment by dominik-reiner** [comment]
@laughingman7743 so essentially sqlalchemy 1.4 isn't and won't be supported with the current version 3.0.3?

**Pull request merged**
