### PR TITLE
Removing filter that required tables to be explicitly external

### PR DESCRIPTION
**Pull request by bradleyhurley**
I don't have easy access to an AWS account for running the tests, but Im happy to make changes or update test if you can provide me with feedback.

### CODE REVIEW

**Comment by laughingman7743** [comment]
The test seems to fail. 🤔 
```
================================================================================================================================================================================================================================ test session starts ================================================================================================================================================================================================================================
platform darwin -- Python 3.10.7, pytest-7.2.0, pluggy-1.0.0
rootdir: /Users/foobar/github/PyAthena, configfile: pyproject.toml
plugins: xdist-3.1.0, cov-4.0.0
collected 451 items                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

tests/test_async_cursor.py .................                                                                                                                                                                                                                                                                                                                                                                                                                                  [  3%]
tests/test_cursor.py .............................................                                                                                                                                                                                                                                                                                                                                                                                                            [ 13%]
tests/test_formatter.py .....................                                                                                                                                                                                                                                                                                                                                                                                                                                 [ 18%]
tests/test_model.py .............                                                                                                                                                                                                                                                                                                                                                                                                                                             [ 21%]
tests/test_sqlalchemy_athena.py ........F.......................................                                                                                                                                                                                                                                                                                                                                                                                              [ 31%]
tests/test_util.py .                                                                                                                                                                                                                                                                                                                                                                                                                                                          [ 32%]
tests/arrow/test_async_cursor.py ..............................                                                                                                                                                                                                                                                                                                                                                                                                               [ 38%]
tests/arrow/test_cursor.py ..................................                                                                                                                                                                                                                                                                                                                                                                                                                 [ 46%]
tests/arrow/test_util.py .                                                                                                                                                                                                                                                                                                                                                                                                                                                    [ 46%]
tests/fastparquet/test_util.py .                                                                                                                                                                                                                                                                                                                                                                                                                                              [ 46%]
tests/filesystem/test_s3.py ....                                                                                                                                                                                                                                                                                                                                                                                                                                              [ 47%]
tests/filesystem/test_s3_object.py ..                                                                                                                                                                                                                                                                                                                                                                                                                                         [ 48%]
tests/pandas/test_async_cursor.py ................................................................................................................                                                                                                                                                                                                                                                                                                                            [ 72%]
tests/pandas/test_cursor.py ...............................................................................................................                                                                                                                                                                                                                                                                                                                                   [ 97%]
tests/pandas/test_util.py ...........                                                                                                                                                                                                                                                                                                                                                                                                                                         [100%]

===================================================================================================================================================================================================================================== FAILURES ======================================================================================================================================================================================================================================
_____________________________________________________________________________________________________________________________________________________________________________________________________________________ TestSQLAlchemyAthena.test_get_table_names _____________________________________________________________________________________________________________________________________________________________________________________________________________________

self = <tests.test_sqlalchemy_athena.TestSQLAlchemyAthena object at 0x11fc2e440>, engine = Engine(awsathena+rest://athena.us-west-2.amazonaws.com:443/pyathena_test_vgftrklp09?location=s3%3A%2F%2Flaughingman7743-athena%2Ftmp%2F&s3_staging_dir=s3%3A%2F%2Flaughingman7743-athena%2Ftmp%2F)

    def test_get_table_names(self, engine):
        engine, conn = engine
        meta = MetaData()
        meta.reflect(bind=engine)
        assert "one_row" in meta.tables
        assert "one_row_complex" in meta.tables
>       assert "view_one_row" not in meta.tables
E       AssertionError: assert 'view_one_row' not in FacadeDict({'boolean_na_values': Table('boolean_na_values', MetaData(), Column('a', BOOLEAN(), table=<boolean_na_value...w_one_row': Table('view_one_row', MetaData(), Column('number_of_rows', INTEGER(), table=<view_one_row>), schema=None)})
E        +  where FacadeDict({'boolean_na_values': Table('boolean_na_values', MetaData(), Column('a', BOOLEAN(), table=<boolean_na_value...w_one_row': Table('view_one_row', MetaData(), Column('number_of_rows', INTEGER(), table=<view_one_row>), schema=None)}) = MetaData().tables

tests/test_sqlalchemy_athena.py:167: AssertionError
================================================================================================================================================================================================================================= warnings summary ==================================================================================================================================================================================================================================
../../Library/Caches/pypoetry/virtualenvs/pyathena-DhQ5A1u5-py3.10/lib/python3.10/site-packages/fastparquet/util.py:20
  /Users/foobar/Library/Caches/pypoetry/virtualenvs/pyathena-DhQ5A1u5-py3.10/lib/python3.10/site-packages/fastparquet/util.py:20: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    PANDAS_VERSION = LooseVersion(pd.__version__)

tests/pandas/test_util.py::test_to_sql_with_partitions
  /Users/foobar/github/PyAthena/pyathena/pandas/util.py:203: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
    for keys, group in df.groupby(by=partitions, observed=True):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================================================================================================================================================================== short test summary info ==============================================================================================================================================================================================================================
FAILED tests/test_sqlalchemy_athena.py::TestSQLAlchemyAthena::test_get_table_names - AssertionError: assert 'view_one_row' not in FacadeDict({'boolean_na_values': Table('boolean_na_values', MetaData(), Column('a', BOOLEAN(), table=<boolean_na_value...w_one_row': Table('view_one_row', MetaData(), Column('number_of_rows', INTEGER(), table=<view_one_row>), schema=None)})
============================================================================================================================================================================================================== 1 failed, 450 passed, 2 warnings in 1668.58s (0:27:48) ===============================================================================================================================================================================================================
```

**Comment by laughingman7743** [comment]
It would be good if you could also fix this test.
https://github.com/laughingman7743/PyAthena/blob/master/tests/test_sqlalchemy_athena.py#L167

**Comment by bradleyhurley** [comment]
@laughingman7743  - Sorry about that. I realized once removing the filter we were then returning `VIRTUAL_VIEW` tables types. I reverted the logic to actually check for the table type being `EXTERNAL` and also added in `MANAGED_TABLE`. This approach should be extensible if needed, but isn't just allowing anything to be considered a table.

**Comment by laughingman7743** [comment]
Thank you. I think it looks like a good change.
I will merge and release v2.21.0.

**Review by laughingman7743 — APPROVED** [review]
LGTM

**Pull request merged**
