### PR TITLE
Support for Python 3.12 (fix #482)

### LINKED ISSUE #482: Support for Python 3.12
https://www.python.org/downloads/release/python-3120/

### PR DESCRIPTION
**Pull request by laughingman7743**

### CODE REVIEW

**Comment by laughingman7743** [comment]
https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean 🤔

**Comment by laughingman7743** [comment]
Markers don't work; there is no decent package manager in Python.
https://github.com/pdm-project/pdm/issues/46
```
    "numpy>=1.24.0,<1.26.0;python_version<\"3.9\"",
    "numpy>=1.26.0;python_version>=\"3.9\"",
```

**Comment by laughingman7743** [comment]
https://github.com/mitsuhiko/rye

**Comment by edgarrmondragon** [comment]
If having lock file isn't a strict requirement for you, you could give Hatch a try (maybe with https://github.com/juftin/hatch-pip-compile)

**Comment by jayceslesar** [comment]
seems weird to have an error on such a low round for PDM? Did that release of numpy get yanked or something?

**Comment by laughingman7743** [comment]
I will try the combination of rye and hatch this weekend.

**Comment by laughingman7743** [comment]
https://github.com/mitsuhiko/rye/issues/206

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/pull/513

**Pull request closed without merging**
