### PR TITLE
SQLAlchemy struct type support

### PR DESCRIPTION
**Pull request by StdCarrot**
Combined with #111 

Implement StructType to support struct type in AthenaDialect.

It working for my case, but I couldn't test your test case: My free tier was expired.. :b

bind processor (to insert) isn't implemented.

It may support nested struct, but have to avoid characters("{", ",", "}") in value for now.

If you want to support the characters in value, have to modify query engine to select struct values separately.

But that is long long way.

### CODE REVIEW

**Comment by StdCarrot** [comment]
It's weird.
Build failed while upload test data.
Is there anything to do for this?

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/pull/95#issuecomment-539780016

**Comment by StdCarrot** [comment]
Okay, but I have no more personal AWS credit for the test.  
I dev and tested this on my company's data set.  
But the reason it was allowed was it could be used for our product development.  
So, I can't sure I can set up travisCI to my repository.  
If I pull request to another branch(like struct-dev) instead of master, can you merge and test?

**Comment by StdCarrot** [comment]
@laughingman7743 
Can I get any answer? 
At least yes or no.

**Comment by laughingman7743** [comment]
Sorry, I don't merge untested code.

**Comment by StdCarrot** [comment]
Even non-master branch?

**Comment by Saqibm128** [comment]
if someone else were to run the tests, would you be able to merge this in?

**Pull request closed without merging**
